name: bloc_demo_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # state
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.1
  get_it: ^7.6.4
  loader_overlay: ^5.0.0
  shimmer: ^3.0.0

  #code gernation realted
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # localization
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  # network
  dio: ^5.3.3
  logger: ^2.0.2
  internet_connection_checker_plus: ^2.7.2
  # routes management
  go_router: ^16.0.0
  # image loading
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  # local storage
  flutter_secure_storage: ^9.2.4
  # core dependencies
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^2.3.9
  flutter_spinkit: ^5.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # code gernation realted
  freezed: ^3.1.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

dependency_overrides:
  intl: ^0.20.2

#analyzer:
#  errors:
#    invalid_annotation_target: ignore


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Extolled Personal Use
      fonts:
        - asset: assets/fonts/extolled_personal_use.otf
    - family: Degular
      fonts:
        - asset: assets/fonts/degular_regular.otf
          weight: 400
        - asset: assets/fonts/degular_medium.otf
          weight: 500
        - asset: assets/fonts/degular_semibold.otf
          weight: 600
        - asset: assets/fonts/degular_bold.otf
          weight: 700
